### ISSUE TITLE
Imported BasicModel does not function as expected 

### ISSUE THREAD

**Issue by fpw23** [sylvainpolletvillard/ObjectModel#105]
Having trouble with defining models outside of my module, importing them in and using them.  Maybe I don't fully understand but I thought if I define an export in one file and import that into another file I should get the same value.  Here is my issue, I created custom basic models in one module:

![image](https://user-images.githubusercontent.com/6162217/52815351-16451600-3064-11e9-806e-ce6bd0273dff.png)

I try importing the StringNotBlank const into another module.  I use that as part of my model definition.  I run the following test:

![image](https://user-images.githubusercontent.com/6162217/52815584-ac793c00-3064-11e9-92c2-854da7432a49.png)

Firstname and Email pass without issues.  Last name errors with "expecting LastName to be StringNotBlank, got String "test"".  

![image](https://user-images.githubusercontent.com/6162217/52815663-e77b6f80-3064-11e9-85e3-60aba9a8f14f.png)

if i change out the value of LastName in userData to match the imported value it works

![image](https://user-images.githubusercontent.com/6162217/52815740-1265c380-3065-11e9-9c00-962369a76e42.png)

![image](https://user-images.githubusercontent.com/6162217/52815757-1bef2b80-3065-11e9-87bc-9c823762c4ce.png)

Why does declaring a const within the same module act differently then the one I imported in from another module?  How can I define  common custom basicmodels and then use them in other modules?

**Comment by sylvainpolletvillard** [comment]
Hello,

I try to reproduce your issue here: https://codesandbox.io/s/j4vx5wmz35
but everything is working fine so far.

Can you provide a minimal reproduction code ?

**Comment by fpw23** [comment]
Thanks for the quick reply!  I will try to get a working example.  Does it matter that I am using mocha and babel?  I saw in other post you said ObjectModel requires ES6 environment

**Comment by sylvainpolletvillard** [comment]
Yes, ObjectModel v3 is using ES6 Proxies, so it won't work on environments that do not support Proxies. But Babel does not transpile Proxies (technically it can't), and the assertion library should not have any impact. However, it is possible that your build tooling configuration is the problem. Are you using Webpack ?

**Comment by fpw23** [comment]
No, the screen shots from above are just using mocha

`mocha --require babel-core/register --require babel-polyfill ./src/**/Schema.Tests.js  --reporter spec --watch`

In the code I am using import/export and async and await so it requires babel

**Comment by sylvainpolletvillard** [comment]
Can you try the code I use in the codesandbox with your setup, so that we can find out if the problem is in your tooling setup or in the code itself ?

**Comment by fpw23** [comment]
ok, i got a test working that matches my environment

https://github.com/fpw23/MochaObjectModelTest

**Comment by sylvainpolletvillard** [comment]
Weird... somehow babel-register is making the `instanceof` operator not working properly when importing from another module

```
console.log("obj.constructor === String", obj.constructor === String)
console.log("Object.getPrototypeOf(obj) === String.prototype", Object.getPrototypeOf(obj) === String.prototype)
console.log("obj instanceof String", obj instanceof String);
```

> obj.constructor === String true
Object.getPrototypeOf(obj) === String.prototype true
obj instanceof String false

I'm afraid this is a bug/limitation in babel, and there is nothing I can do on the library to fix that :( But I'm curious to know what exactly happens here

**Comment by fpw23** [comment]
Ok, what I may try is upgrading to babel 7 and see if that makes a difference, will let you know.  Thanks for all the help!

**Comment by sylvainpolletvillard** [comment]
Don't bother, I just tried that and it doesn't fix it

**Comment by fpw23** [comment]
Doh!  well my one last question then, I tried taking babel out of mocha so I could see the raw results and this is what I got for the Schema.Test.js file
![image](https://user-images.githubusercontent.com/6162217/52825212-7ac29e00-3081-11e9-9b61-4411f2e692ad.png)

![image](https://user-images.githubusercontent.com/6162217/52825007-bad55100-3080-11e9-9614-9af2a2783aa5.png)

and here is the raw code for the Schema.js

![image](https://user-images.githubusercontent.com/6162217/52825073-f1ab6700-3080-11e9-9d91-4bc2b0aaefcd.png)

All there lines look the same, the two within the module work but the on import in does not.  Does the wait it "var StringNotBlank = exports.StringNotBlank =" in front of the function make a difference?

**Comment by sylvainpolletvillard** [comment]
I noticed this:

```
var _Schema = require('./Schema');
var _objectModel = require('objectModel');
console.log(_Schema.StringNotBlank instanceof _objectModel.Model) // false ????
```

Maybe it's because objectmodel is required twice, they don't share the same reference to `Model` ?

**Comment by sylvainpolletvillard** [comment]
lol this is stupid

https://github.com/fpw23/MochaObjectModelTest/blob/master/src/Core/Schema.Tests.js#L5

Replace `objectModel` with `objectmodel` and the test pass

Looks like node can deal with mixed case for module names, except it doesn't use the same cache if the case is different

**Comment by fpw23** [comment]
Thank you!  👍 🥇 😄 

I looked at this code all day yesterday and never noticed that.
