### ISSUE TITLE
Custom error collectors catching all errors and not just the first one

### ISSUE THREAD

**Issue by johncrenshaw** [sylvainpolletvillard/ObjectModel#11]
The current validators always throw on the first failure and give poor access to error information. Validators also provide no human readability options.

- Asserts need an optional human readable description. The easiest way to do this seems to be with with an Assert class, similar to the Model class, that can be used to define an assertion callback, as well as a human readable description.
- Types need an optional human readable description. Current readability is only tolerable for simple types, but not much help when you start stacking on assertions. Under the current strategy where only the first error is thrown (and where that is the assert, in assertion failure) this need is somewhat hidden, but it becomes more apparent once error information is collected in a more meaningful way. I anticipate working around this in my code by adding a Model.describeModel() method (or something similar), and overriding toString().
- checkDefinition should be refactored to collect errors rather than throwing a single error. This is very important for complex models, or situations where you care about all errors, not just the first. These changes could then be exposed either in validate, or via a new method. There are a few ways this can be done. If you want I can send you what I put together, which is highly flexible.

**Comment by sylvainpolletvillard** [comment]
These are good points, thank you.

I will split this issue in two parts:
- human readable descriptions for models and assertions
- collecting and returning all errors instead of the first one

The first one can be easily done. For my personal usage, properly named assertion functions have been good enough so far but I can understand why you may need longer and more descriptive error messages. I need to think about the API for this.

The second one will need stronger refactoring. It definitely makes sense through.

**Comment by johncrenshaw** [comment]
The collection is actually a relatively trivial change when you get down to it. Basically refactor checkDefinition to accept optional fnTypeError and fnAssertFailed collectors as callbacks:

```
        function checkDefinition(obj, def, path, stack, fnTypeError, fnAssertFailed){
            if(isLeaf(def)){
                def = parseDefinition(def);
                var assertionFailures = [];
                for(var i= 0, l=def.length; i<l; i++){
                    if(checkDefinitionPart(obj, def[i], path, stack, null, function(obj, assertion, path, stack){
                        assertionFailures.push([obj, assertion, path, stack]);
                    })){ return true; }
                }
                // Push assertion failures to the error callback because they may indicate
                // nearly-valid intended states, so information about the specific assrtions
                // that failed individual types is potentially more valuable than knowing that
                // the overall type failed.
                if (fnAssertFailed)
                {
                    for (var a = 0; a < assertionFailures.length; a++)
                    {
                        fnAssertFailed.apply(null, assertionFailures[a]);
                    }
                }
                if (fnTypeError)
                {
                    fnTypeError(obj, def, path, stack);
                }
                return false;
            } else {
                var ret = true;
                Object.keys(def).forEach(function(key) {
                    var val = obj != null ? obj[key] : undefined;
                    if (!checkDefinition(val, def[key], path ? path + '.' + key : key, stack.concat(val), fnTypeError, fnAssertFailed))
                    {
                        ret = false;
                    }
                });

                return ret;
            }
        }

        function checkDefinitionPart(obj, def, path, stack, fnTypeError, fnAssertFailed){
            if(obj == null){
                return obj === def;
            }
            if(Model.instanceOf(def, Model)){
                var indexFound = stack.indexOf(def);
                if(indexFound !== -1 && stack.slice(indexFound+1).indexOf(def) !== -1){
                    return true; //if found twice in call stack, cycle detected, skip validation
                }
                return checkDefinition(obj, def.definition, path, stack.concat(def), fnTypeError, fnAssertFailed) && matchAssertions(obj, def.assertions, path, stack.concat(def), fnAssertFailed);
            }
            if(def instanceof RegExp){
                return def.test(obj);
            }

            return obj === def
                || (isFunction(def) && obj instanceof def)
                || obj.constructor === def;
        }

        function matchAssertions(obj, assertions, path, stack, fnAssertFailed){
            var ret = true;
            for(var i=0, l=assertions.length; i<l ; i++ ){
                if(!assertions[i](obj)){
                    if (fnAssertFailed)
                    {
                        fnAssertFailed(obj, assertions[i], path, stack);
                    }
                    ret = false;
                }
            }
            return ret;
        }

        // Expose the power of the collector based definition checking in the model
        Model.prototype.checkDefinition = function (fnTypeError, fnAssertFailed) {
            return this.checkDefinition(fnTypeError, fnAssertFailed);
        };

```

Then something like this matches the old behavior:

```
        Model.prototype.throwErrors = function () {
            return this.checkDefinition(function(obj, def, path, stack){
                throw new TypeError(path, "expecting " + (path ? path + " to be " : "") + def.map(function(d){ return toString(d); }).join(" or ")
                + ", got " + (obj != null ? bettertypeof(obj) + " " : "") + toString(obj) );
            }, function(obj, assertion, path, stack){
                throw new TypeError(path, "an assertion "+(path ? "for "+path : "of the model")+" is not respected: "+assertion);
            });
        };
```

And something like this can collect and return errors:

```
        Model.prototype.collectErrors = function () {
            var errors = {};
            var addError = function (path, error) {
                if (typeof path == 'undefined' || !path)
                {
                    path = '_';
                }
                if (typeof errors[path] == 'undefined')
                {
                    errors[path] = [];
                }
                errors[path].push(error);
            };
            this.checkDefinition(function(obj, def, path, stack){
                addError(path, "expecting " + (path ? path + " to be " : "") + def.map(function(d){ return toString(d); }).join(" or ")
                + ", got " + (obj != null ? bettertypeof(obj) + " " : "") + toString(obj) );
            }, function(obj, assertion, path, stack){
                addError(path, "an assertion "+(path ? "for "+path : "of the model")+" is not respected: "+assertion);
            });
            return errors;
        };
```

**Comment by sylvainpolletvillard** [comment]
Yes, I was thinking of something like this. An error collector callback can be a good idea for error tracking in production for example.
I need to think about a generic error format that can suit to all the different kinds of errors we are handling (currently 5 different messages). `path` is not always defined, `stack` is an internal argument used for cycle detection. As first thought, I would go with `{ expected, received, message }`. The call stack provided by exceptions is really useful though.
Also, these collectors must not intefere with model.test calls. Not sure what to do with model.validate
Not that trivial as it seems :smiley:

**Comment by johncrenshaw** [comment]
If it were me, I'd make model.validate optionally accept the collector(s), and if not provided use throwing collectors (so the same as the current behavior).

It is critical that the collectors have access to path, because that is the only way errors can be organized according to the part of the model that failed. This is helpful for a number of things the validation may be used for, including assisting with form validation. This also becomes important for the recursion in checkDefinition (I discovered an error in the code I previously posted, I have corrected it, but the correction wouldn't have been possible if the collector didn't have path.)

A simpler {expected, received, message} collector has it's appeal, especially in being able to reduce the solution to a single collector, but I don't think it is a sufficient substitute for a pair of more raw collectors, since it hides important information about the error.

**Comment by sylvainpolletvillard** [comment]
:+1: for model.validate(object, [collector])

Sure, even if the path is specified in the message, I will put it in a separate `path` property for automatic error handling. For some errors, like Array models validation, retrieving the full path is more tricky. This is on my todo list for a long time.

**Comment by sylvainpolletvillard** [comment]
Rewriting checkDefinition is not satisfying since we have other sources of errors around, and checkDefinition can be used for unrelated validation sub-processes like model.test. I am working on another approach from the top entry points rather than the bottom endpoints. This will take some time, but stick around for 1.2.

**Comment by sylvainpolletvillard** [comment]
added in v2.0 :+1:
