### ISSUE TITLE
浏览器版本放弃的措手不及

### ISSUE THREAD

**Issue by maozhenzhong** [sylvainpolletvillard/ObjectModel#111]
浏览器版本放弃的措手不及，一个好的开源项目是不是要向下兼容，我整个项目用ObjectModel3版本，结果不兼容IE浏览器，这让重新修改项目成本得有多大，兼容IE浏览器的版本老的不能直接使用，唉，坑爹的库。

**Comment by sylvainpolletvillard** [comment]
Please post your issues in English, I don't speak chinese.

Browser support is only changed on **major** versions, and only when necessary for technical reasons. The browser support is clearly stated on the website: http://objectmodel.js.org/#common-questions ; and also stated in the Breaking Changes section of every new major release: https://github.com/sylvainpolletvillard/ObjectModel/releases/tag/v3.0.0

If you have to support IE11, you'll have to stick with ObjectModel v2. The v2 documentation is still available here: http://objectmodel.js.org/docs/v2/
