### ISSUE TITLE
performance: extended getters getting called 3 times internally

### ISSUE THREAD

**Issue by gotjoshua** [sylvainpolletvillard/ObjectModel#120]
So, we used to use ObjectModel for both our data objects (OMs) and ViewModels (VMs)
The VM was a very simple ObjectModel that only needed to check that it's _om prop was an instance of the correct OM.
Then the VM is extended (as the model is not "sealed") with many getters that do not need to be validated.
Today we discovered that the getters are called 3 times internally to ObjectModels get function.
We promptly transformed our BaseVM into a normal object and see noticeable differences across all UI interaction.

I made a code pen to illustrate:
https://codepen.io/gotjoshua/pen/qBdmJQP

![getterCalled3x](https://user-images.githubusercontent.com/8686454/75563307-0ff0c480-5a42-11ea-8558-18c183d180fd.png)

I know that using ObjectModel comes at a cost, but 3x on all calls to getters that don't need validation at all seems excessive.

**Comment by gotjoshua** [comment]
I think simply caching o[key] in a const before [this code block at L#278](https://github.com/sylvainpolletvillard/ObjectModel/blob/master/src/object-model.js#L278) could at least help a bit:

```js
if (o[key] && has(o, key) && !isPlainObject(defPart) && !isModelInstance(o[key])) {
  o[key] = cast(o[key], defPart) // cast nested models
}

if (isFunction(o[key]) && key !== "constructor" && !privateAccess) {
  return grantPrivateAccess(o[key])
}

if (isPlainObject(defPart) && !o[key]) {
  o[key] = {} // null-safe traversal
}
```

**Comment by sylvainpolletvillard** [comment]
That seems totally right. Thanks for the investigation, will try to push a new version today

**Comment by sylvainpolletvillard** [comment]
Fixed in v4.0.6

**Comment by gotjoshua** [comment]
Is there a tag for that?

**Comment by sylvainpolletvillard** [comment]
Added a git tag.

**Comment by gotjoshua** [comment]
I [made another pen](https://codepen.io/gotjoshua/pen/oNXwWjz) that does 1000 instantiations and 1000 calls to a getter that also uses another getter.
The difference is noticeable between 4.0.6 and 4.0.5!

However, the performance compared to normal objects is still a bit disturbing:
### 4.0.5
![4 0 5](https://user-images.githubusercontent.com/8686454/75623765-5a3e8680-5ba5-11ea-971f-96db85127d0a.png)

### 4.0.6
![4 0 6](https://user-images.githubusercontent.com/8686454/75623771-7fcb9000-5ba5-11ea-94f7-574dfaec208a.png)
