### ISSUE TITLE
Package objectmodel has been ignored because it contains invalid configuration

### ISSUE THREAD

**Issue by anutting** [sylvainpolletvillard/ObjectModel#134]
Hello,

I'm attempting to use Objectmodel within a React Native project. The metro server is throwing this warning on start-up. The package seems function correctly in development, but the messaging is a bit concerning.

warn Package objectmodel has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in myproject/node_modules/objectmodelpackage.json

Is anybody using this package in a live React Native app?

Thanks

**Comment by sylvainpolletvillard** [comment]
This seems like a common problem for many packages with React Native: https://github.com/react-native-community/cli/issues/1168

I guess it should be fixed on React Native tooling instead ? If there is an easy fix, i take it

**Comment by sylvainpolletvillard** [comment]
Confirmed it's a bug on React Native side. You'll have to wait for a fix on their side
