### ISSUE TITLE
Feature request: Register as a Bower package?

### ISSUE THREAD

**Issue by kokujin** [sylvainpolletvillard/ObjectModel#14]
It would be nice if one could install this a s a bower package.

**Comment by sylvainpolletvillard** [comment]
I don't know about this. Project management and development of Bower has been chaotic these years,  while NPM has never been so popular. 
Also, you probably use npm to install Bower, and ObjectModel is available on npm, so I don't really see the point.

**Comment by sylvainpolletvillard** [comment]
Since no one else asked for it, and the funding of Bower is currently [almost nonexistent](https://salt.bountysource.com/teams/bower), I decided to not make a bower package and stick with npm. I will reconsider this if many people ask for it.
