### ISSUE TITLE
Getting property types from a model instance

### ISSUE THREAD

**Issue by kokujin** [sylvainpolletvillard/ObjectModel#15]
How can I get the property type of a model instance attribute? Using the example snippet below
````
var User = new Model({
      name: String,
      female: [Boolean],
      birth: Date,
      choices: ['a', 'b', 'c']
   });

    var joe = new User({
      name: "Joe",
      birth: new Date(),
      choices: 'c'
   });
````

How can I get the attribute type of name from the instance "joe"? Using typeof I get a type of "function" which is actually not correct. Thanks

**Comment by sylvainpolletvillard** [comment]
Types in object models are more complex than the simple types returned by typeof. You can use strict comparison : User.definition.name === String

From an instance,  it is currently not possible to retrieve the associated model without a reference to this model. Would it be useful to you? Can you give me more details about your use case? Thanks

**Comment by kokujin** [comment]
It would be useful. My present use case at the moment is generating different UI widgets depenending on the type of field.

**Comment by sylvainpolletvillard** [comment]
I see. To do this,  I need to store the model information inside the object, which means adding a hidden property to the instances objects . The other option is to maintain a store of all the instances of each model. None of these options seems a good idea to me. I'll try to find something better. Any ideas? 

The other option for your usecase would be to use conditions and instanceof tests

**Comment by kokujin** [comment]
I'll try to think of something. I am am just keeping the object passed to the Model constructor for later use.

**Comment by sylvainpolletvillard** [comment]
Sure, you can also add this hidden property manually on your instances.

**Comment by sylvainpolletvillard** [comment]
Okay I found a way to do this right now:

````
var modelOfJoe = Object.getPrototypeOf(joe).constructor;
modelOfJoe === User; // true
modelOfJoe.constructor.definition.name === String; // true
```

Maybe I'll add a `Model.getFromInstance` function in the next version.
