### ISSUE TITLE
How to add custom methods to a Model?

### ISSUE THREAD

**Issue by DaviidMM** [sylvainpolletvillard/ObjectModel#152]
Using for example a `ObjectModel`, how can I add method or functions to it?

In the following example, how can I add or create the method `getColor()` so it returns the`color` property of the object `davidm` ?

```js
const Person = ObjectModel({
  name: String,
  color: String
})

const davidm = Person({
  name: 'David',
  color: 'red'
})

console.log(davidm.getColor())
```

Thank you beforehand 😄

**Comment by sylvainpolletvillard** [comment]
Sorry for the late answer,

You can add methods through [prototypal delegation](https://dev.to/aman_singh/an-easy-explanation-to-prototypal-delegation-in-javascript-3ok2) in JavaScript. Models are the constructors of your objects:

```js
const Person = ObjectModel({
  name: String,
  color: String
})

Person.prototype.getColor = function(){
  return this.name
}

const davidm = Person({
  name: 'David',
  color: 'red'
})

console.log(davidm.getColor())
```

You can also use the class operator:
```js
class Person extends ObjectModel({
  name: String,
  color: String
}){
    getColor(){
        return this.color 
    }
}

const davidm = new Person({
  name: 'David',
  color: 'red'
})

davidm.getColor()
```
