### ISSUE TITLE
objectmodel@4.4.0: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by bacloud23** [sylvainpolletvillard/ObjectModel#158]
Hi @sylvainpolletvillard,
The library crashes the whole installation using yarn on node version 16.

Is node 17 really a constraint for this library ? 

Thank you :)

**Comment by sylvainpolletvillard** [comment]
No this looks like an oversight on my part, sorry. I will change that immediately.

**Comment by bacloud23** [comment]
ok thank you !

**Comment by sylvainpolletvillard** [comment]
Released in v4.4.1, new minimal versions:
```
"engines": {
    "npm": ">=6.14",
    "node": ">=13"
  },
```

I noticed some minor issues with the build tooling on older versions of Node, but this should not impact you.
