### ISSUE TITLE
get objectmodel added to typia benchmarks

### ISSUE THREAD

**Issue by gotjoshua** [sylvainpolletvillard/ObjectModel#165]
Would be cool to get objectmodel added to @samchon 's comparisons

they are open for a PR:
https://github.com/samchon/typia/issues/521

Related to [my longest open issue yet ](https://github.com/sylvainpolletvillard/ObjectModel/issues/121)

**Comment by sylvainpolletvillard** [comment]
Comparing one-time validation pass libraries with proxy-based continuous validation is like apple to oranges. It looks like a cool library though if you need single-point perf-critical runtime validation.

**Comment by gotjoshua** [comment]
> proxy-based continuous validation

good point.


still, OM can do a lot of the stuff they can do, and more.

**Comment by sylvainpolletvillard** [comment]
Typia, zod and other validation libraries are like security checks: they scan your objects once and forget about it when they are done. ObjectModel is like a bodyguard escort: they are bound to your objects and will check every interaction with them from now on.

**Comment by gotjoshua** [comment]
> like a bodyguard

Nice analogy. : )
