### ISSUE TITLE
pre/post process some datas ?

### ISSUE THREAD

**Issue by gordielachance** [sylvainpolletvillard/ObjectModel#169]
Is it possible to process some date before or after the validation is done ?

    function isDateString(value){
      // parse the string into a date object
      const date = new Date(value);

      // if the parsing failed or the resulting date is invalid, throw an error
      return  !isNaN(date.getTime())
    }

    export const DateStringModel = BasicModel(String).assert(isDateString);

    export const Playlist = new ObjectModel({
    	//...
    	date: [DateStringModel],
    	//...
    });

So the validation checks that the data is a valid date string.  But them, how can I cast this value to a Date ?

**Comment by sylvainpolletvillard** [comment]
I'm not sure why you expect here, you can do this pre/post process with your own logic:

```
YourModel(preprocess(data))
postprocess(YourModel(data))
```

**Comment by sylvainpolletvillard** [comment]
closed after inactivity
