### ISSUE TITLE
I can't find a npm module for this library

### ISSUE THREAD

**Issue by doodzik** [sylvainpolletvillard/ObjectModel#2]
hey there,

is there a npm module available  for this library and if not can you publish it?
I would love to use your library without the need to download the dist folder.

**Comment by sylvainpolletvillard** [comment]
Hi,
I'm going to publish it to npm soon. In the meantime, you can refer to this github respository in your package.json:

```
"dependencies": {
   "objectmodel": "sylvainpolletvillard/ObjectModel"
}
```
https://docs.npmjs.com/files/package.json#github-urls

**Comment by doodzik** [comment]
:+1: thanks :)
If you want any help let me know!

**Comment by sylvainpolletvillard** [comment]
You can help in many ways: leaving feedback, exchanging ideas, talking about it around you...

**Comment by sylvainpolletvillard** [comment]
done: https://www.npmjs.com/package/objectmodel
