### ISSUE TITLE
Is there a way to stop extra keys in the Object model?

### ISSUE THREAD

**Issue by coolkau** [sylvainpolletvillard/ObjectModel#21]
I was wondering if there is an easy way to prevent extra keys in the object:

This example should throw an error that "two" is not defined in the model.
var test = Model({one:String})
test({one: "one", two: "two"})

Thank you very much in advance and apologies if I missed this in the documentation.

**Comment by sylvainpolletvillard** [comment]
Hi coolkau,

This problem will be fixed in Object Model 3, which you can have a preview on the next branch : https://github.com/sylvainpolletvillard/ObjectModel/tree/next ; it is already functional, and I am currently working on adding new features.

It is related to how object models are proxified in order to detect and check the validity of the mutations of object models instances. There are two technical ways to do this: property getters (ECMAScript 5) or Proxy (ECMAScript 6). With ObjectModel 2, getters are used because of the broader browser support. But getters only work for properties declared in the model definition, they cannot detect unexpected, undeclared properties. This is solved by Proxy which let us catch any operation on an object. 

You can see the browser support for Proxy here : http://caniuse.com/#search=proxy ; Object Model 3 will use Proxies everywhere, which means the browser support will be significally reduced (no IE, no older Chrome/FF).

**Comment by coolkau** [comment]
Hi Sylvian,

sound great, though the lacking Mac support will hurt a bit I would guess...

**Comment by sylvainpolletvillard** [comment]
Fortunately Safari 10 does much better and fully supports Proxies. But yes, it will take some time before Proxy and ES6 get enough support for a large audience.

**Comment by coolkau** [comment]
As a last word, as I have now played with it for a while.
The tool is really awesome. It really makes my life so much easier. I spotted already so many tiny inconsistencies when passing objects into functions, for which I use it mainly. However, the extra keys detection is also really important and is heavily missed when trying to debug in in early stages. I built a (bit sloggish) second test for that:

function testForExtraKeys(type, list) {
    var keys = Object.keys(list);
    var keysType = Object.keys(type.definition);
    if (ifComplementAny(keysType, keys)) {
        var wrongKeys = complement(keysType, keys).join(", ")
        throw "The input contains keys which are not defined in the model: " + wrongKeys;
    }
}

Lets hope that the browser support is growing so I can get rid of this workaround.

**Comment by sylvainpolletvillard** [comment]
Okay, I'm going to push some modifications that I think will help you.

<dl>
	<dt>v2.1</dt>
				<dd>assertions are now inherited from <code>Model.prototype</code>, which enables you to add global assertions</dd>
				<dd>assertions now require to return <code>true</code> to validate. Truthy values do not pass anymore</dd>
				<dd>assertions error messages can now be functions called with the assertion result as argument</dd>
</dl>

This will enable you to do that:

![image](https://cloud.githubusercontent.com/assets/566536/16707860/737b51d6-45de-11e6-8a43-931bcd2eb244.png)

You will still have to manually call validate() on 2.x models when adding undeclared properties outside of the constructor. With ObjectModel 3, it is automatically handled:
![image](https://cloud.githubusercontent.com/assets/566536/16707868/b682b820-45de-11e6-8973-693d32480daf.png)

This is already done on the next branch. Expect it to land in a day or two :+1:

**Comment by sylvainpolletvillard** [comment]
v2.1 released :tada: 

Your feedback is much appreciated

**Comment by coolkau** [comment]
Thanks a bunch.  I wont have time to fully test this until next week, but from what I see I think it does exactly what I want it to do. 

I have several critical points at which I would like to make sure that all is in place and when reaching these points my model is complete. So I am not too worried about "undeclared properties outside of the constructor". 

To give you a specific reason why I am after the "extra parameters":
My main concern are typos such as "obj.on" instead of  "obj.one" (or refactoring). The "normal 2.x" validation does not trigger if the "one" is an optional parameter... and I have a lot of optional parameters...

So thanks again; unless you hear from me again shortly, I will be very happy about this new feature and the quick fix!

**Comment by sylvainpolletvillard** [comment]
Yes, undeclared properties checking is a long time issue, and one of the main reasons I made a Proxy-only version for ObjectModel v3. This way it will catch typos everywhere. Until then, you can use validate() at your critical points if you feel you need it.

**Comment by sylvainpolletvillard** [comment]
I think this issue can be considered resolved with the 2.1 changes and the incoming 3.0 changes. Feel free to open another issue if you have any other question.
