### ISSUE TITLE
Requires root for no reason

### ISSUE THREAD

**Issue by carlosl** [sylvainpolletvillard/ObjectModel#22]
Currently the post install script does a global install (npm -g) of grunt, which would require me to do a sudo npm install of objectmodel. I don't believe a global install should be required for something that is supposed to be used as a dev dependency. Why not just include grunt as a dependency?

For now just going to pull it from repo.

**Comment by sylvainpolletvillard** [comment]
I copied this setup from another repo. I think it was indended for newbies, because most of the grunt documentation assumes grunt is installed globally. Let's make it a local dependency and see if people complain :smile:

**Comment by sylvainpolletvillard** [comment]
closed with https://github.com/sylvainpolletvillard/ObjectModel/commit/6d3ded59e3d4a6c2504fb8febbc50cc5ecca128b
