### ISSUE TITLE
Is it possible to validate without throwing an error?

### ISSUE THREAD

**Issue by talyssonoc** [sylvainpolletvillard/ObjectModel#31]
I'd like to have something link an `isValid()` method instead of throwning an error right from the constructor, for example:

```
const NumberModel = Model(Number);
const number = new NumberModel('42'); // do not throw TypeError
number.isValid(); // returns false
```

Is is achievable with this lib?

Btw, nice lib!

**Comment by sylvainpolletvillard** [comment]
Hi,

I think you are looking for `let isValid = NumberModel.test('42')`

**Comment by talyssonoc** [comment]
Oh, you're right! I was looking for a way to do that directly from the instance but it will work too. Thanks! :smile:

**Comment by sylvainpolletvillard** [comment]
Models instances are necessarily valid, this is the whole point of strong type checking. If an operation on a model instance makes it invalid, the operation will not be applied.
