### ISSUE TITLE
ObjectModel defaults are not set when creating Model.Array(ObjectModel)

### ISSUE THREAD

**Issue by oleg-l** [sylvainpolletvillard/ObjectModel#33]
Example:
```
var M = new Model({
    n : Number,
    s : String,
    f : Model.Function().return(String)
}).defaults({
    f : function() { return 'bbb'; }
});

var m = new M({ n : 1, s : 'aaa' }); // Ok, function f() is set from defaults
console.log(m.n, m.s, m.f()); // Ok

var A = Model.Array(M);
var a = new A([{ n : 1, s : 'aaa' }]);
// throws Uncaught TypeError: expecting Array[0].f to be "Function", got undefined(…)
```

**Comment by sylvainpolletvillard** [comment]
Currently, Array models items are not automatically casted to model instances based on the Array model definition. So the current way to do this would be `new A([ M({ n : 1, s : 'aaa' }) ]);`

But I think it makes sense to add automatic model casting here too. It is a similar issue to https://github.com/sylvainpolletvillard/ObjectModel/issues/24 .

I guess I should bring automatic model casting to every kind of Model, and use the same strategy to find the suitable model and warn when ambiguous.

**Comment by oleg-l** [comment]
Ok, I see. Don't you think, it would be useful to add user-defined constructor argument casting? Something like this:
```
var M = new Model({
    s : String
}).cast({
    s : function(value) { return value.toString() }
});
var m = new M({ s : new Date() }); // Ok, s was converted to string
```
But this idea is for another issue, I think

**Comment by sylvainpolletvillard** [comment]
Yes, property casting is a different issue and I would recommend using a factory function for this, instead of the Model constructor. See _How do I declare a constructor function to be called on instanciation before validating my model ?_ in http://objectmodel.js.org/#common-questions

**Comment by oleg-l** [comment]
Yes, I do it that by. But factories make model definition longer. I like your 'defaults({...})' style. Casting that way would make code more compact. Thank you! Closing issue.

**Comment by sylvainpolletvillard** [comment]
Every library is a tradeoff between user code size and API size. I think factory functions are the best compromise, since they are very flexible and straight-forward to use. But it should be relatively easy to extend the library the way you want and add a `Model.prototype.cast` function.

**Comment by sylvainpolletvillard** [comment]
Automatic model casting will be available in v2.5 for array items and function arguments and return value

**Comment by sylvainpolletvillard** [comment]
Your code example is now valid since v2.5.2 👍

**Comment by oleg-l** [comment]
Super!
