### ISSUE TITLE
async usage of Model.Array

### ISSUE THREAD

**Issue by rubtk** [sylvainpolletvillard/ObjectModel#34]
Hello, I am trying to return instance of Model.Array asynctonius via callback or Promise in node.js.
Sadly, i can not do that, and there is no error written by node. I can return normal models, but can not return Array model. Is that bug?

**Comment by sylvainpolletvillard** [comment]
Hi,
Can you provide a code example please ?

**Comment by rubtk** [comment]
Thanks for reply!
sample code is here => http://pastebin.com/aSQc4L3f

**Comment by sylvainpolletvillard** [comment]
```
   // But printing using console.log works good
  // It prints :
  // model [
  // model { reqNumber: [Getter/Setter], description: [Getter/Setter] },
  // model { reqNumber: [Getter/Setter], description: [Getter/Setter] },
  // ...
  console.log(instanceArray);
```

So based on this console log, it looks like the array is correctly instanciated.

Searching for `Illegal Access` errors on Node, I found different weird cases where the error occured only when trying to debug. For example : https://github.com/node-inspector/node-inspector/issues/864

Do you have the same error when running this outside of VS Code ? From a terminal for example ?

**Comment by rubtk** [comment]
Thanks for help, I have started app using console and it works! My node version is 6.9.1. Do that connected with node or debug tools? I would try to use command line node js debugger.

**Comment by sylvainpolletvillard** [comment]
This is a bug on VS Code. You can found the ticket here:
http://stackoverflow.com/questions/39710014/debuging-es6-proxy-as-property-internal-error-illegal-access
https://github.com/Microsoft/vscode/issues/12749

There is nothing I can do on my side, you'll have to wait for a fix on Visual Studio Code.
