### ISSUE TITLE
Constructor should ignore unknown properties

### ISSUE THREAD

**Issue by yamsellem** [sylvainpolletvillard/ObjectModel#36]
Properties not defined in the model should not be set on the instance — but, as this test shows, they are still added to the properties.

```javascript
const test = require('ava');
const Model = require('objectmodel');

const Record = new Model({
    name: String
});

test('Constructor should ignore unknown properties', t => {
    const raw = {
        name: 'paul',
        surname: 'simon'
    };

    const record = new Record(raw);
    t.truthy(record.name);
    t.falsy(record.surname); // this test fails, surname = "simon" but it should not
});
```

**Comment by sylvainpolletvillard** [comment]
ObjectModel does not enforce you to use strong type checking on *all* of your properties. It only validates the instance according to its model definition, but you are free to set undeclared properties in your instances just like you would do with a regular JavaScript object. 

This is an intended feature and **is also essential to progressively bring strong dynamic typing to existing projects or external dependencies.**

However, you can decide to forbid undeclared properties on all object models with a simple assertion. Check this example for [the official docs](http://objectmodel.js.org/#doc-assertions):

```javascript
Model.Object.prototype.assert(function noUndeclaredProperties(obj) {
	var modelDefinition = this.definition;
	var extraKeys = Object.keys(obj).filter(function(key){
		return modelDefinition.hasOwnProperty(key) === false;
	});
	if(extraKeys.length === 0) return true; // validate assertion
	else return extraKeys; // pass information to the error message
}, function(extraKeys){
	return "These properties are not defined in the model: " + extraKeys.join(', ');
})

// Example usage
var Order = Model({ price: Number });

var expectedOrder = Order({ price: 42.50 });

var receivedOrder = Order({
	price: 42.50,
	taxes: 8.33,
	deliveryCost: 15.00
});
TypeError: These properties are not defined in the model: taxes, deliveryCost
```

Hope it helps

**Comment by sylvainpolletvillard** [comment]
Validation steps are not supposed to *mutate* the original object, only accept or reject the initial object or the mutation. If ObjectModel mutates the object by removing undeclared properties for example, should it validate again a second time now that the object has been modified ? What if there is an assertion on the number of properties of this object ?

This lead to many questions so I would recommend to do this outside of ObjectModel, through a factory function (see ["How do I declare a constructor function to be called on instanciation before validating my model ?"](http://objectmodel.js.org/#common-questions))

Also, note that ignoring these properties without notice may lead you to dead code. Maybe an error or an explicit console warning would be better suited, but I am not aware of your usecase.
