### ISSUE TITLE
Use in Node Project with require

### ISSUE THREAD

**Issue by pankajpatel** [sylvainpolletvillard/ObjectModel#4]
`
var Model = require('objectmodel');
`

I think you should also make it available to be used in Node projects.

**Comment by sylvainpolletvillard** [comment]
Right. I will add a main field to package.json pointing to the UMD bundle, or maybe a new one specific for Node.

Do you see anything that could be added or modified in the library for a better use with nodejs ? I'm interested in any feedback on how the library is used, to think about future developments

**Comment by sylvainpolletvillard** [comment]
Done in v1.1.5. I close the issue but I am still interested in your feedback on ObjectModel with Node.js

**Comment by pankajpatel** [comment]
Well the use case to use objectModel in node.js is in Express apps; as from the client side I am gonna receive some data (let form data) and I would need to validate it first before going ahead to operate on that data. 

For the moment I chose https://github.com/geraintluff/json-model to do so, but I think your lib is pretty fit for basic object modeling.

I would give it a try again.

**Comment by sylvainpolletvillard** [comment]
Cool :) I personally create one file per model, so that I can require them on both server or client side. For example: https://github.com/sylvainpolletvillard/t-pex/blob/master/src/editor/models/config.js
