### ISSUE TITLE
[question] How to set up composed key

### ISSUE THREAD

**Issue by beebase** [sylvainpolletvillard/ObjectModel#47]
Thank you for this absolutely AWESOME package! Exactly what I was looking for. Since 99% of (my) debugging always boils done to sending/receiving messed up params, args , objects etc. you can imagine what a time saver this is going to be.
Also excellent documentation which I admittedly haven't completely absorbed yet. So maybe this question is already answered somewhere in the docs.
I have a _key that defaults to a new uuid() 
Now _id has to be composed like  'company/'+_key
How can I accomplish that?
```
createKey() {
return uuid()
}
```
```
new Model({
_key : String,
_id : String
...
}).defaults({
_key : createKey(),
_id : 'company/'+ _key ???
})
```

**Comment by beebase** [comment]
btw: I'm currently handling this like:

```
let _id                    = ''
const createKey            = () => {
  const newKey = uuid()
  _id          = 'skill/' + newKey
  return newKey
}
```

```
new Model({
_key             : String,
_id              : String,
...
}).defaults({
_key             : createKey(),
_id              : _id,
...
```

**Comment by sylvainpolletvillard** [comment]
There are two ways to do this : 
1. _id is a **computed property**, so you declare it as a *getter*

```javascript
var MyModel  = new Model({
_key : String,
_id : String
}).defaults({
_key : createKey(),
get _id(){ return 'company/'+ this._key }
})
```

This means you cannot reassign _id value, only _key

2. _id is defined by default based on another property:   initiate _id through a factory function

```javascript
var MyModel = new Model({
_key : String,
_id : String
}).defaults({
  create: function(){
    var key = createKey();
    return new MyModel({ _key: key, _id: 'company/'+ this._key })
  }
})

var myModelInstance = MyModel.create()
```

**Comment by sylvainpolletvillard** [comment]
A third option is to use ES6 classes and constructor. This is something that will be easier in v3, but only useful if you are targeting ES6-compliant browsers.
