### ISSUE TITLE
database _pk is handled as private

### ISSUE THREAD

**Issue by beebase** [sylvainpolletvillard/ObjectModel#48]
I have a naming collision. My database (ArangoDb) only accepts _key as primary key.
When I create a record offline I have to add {_key : uuid} in order to sync with the db when coming online again.  if _key is missing in the record, the db will create it's own _key.

The problem is that ObjectModel sees _key as private and strips it when the record is sent to the db server.
 How can I solve this?

**Comment by sylvainpolletvillard** [comment]
Hi,

You can customize the convention for private keys. For example:

```
Model.conventionForPrivate = function(key){ return key.startsWith("private_") }
```

In the next version of ObjectModel, you will be able to set this convention specifically for one model. Currently it applies on all models.

**Comment by beebase** [comment]
I couldn't find an example in the docs but I guess this is the solution
```
Model.conventionForPrivate = (key) => { 
    return key[0] === '#' 
}
```

**Comment by sylvainpolletvillard** [comment]
If you don't want private at all, you can also `return false`

**Comment by beebase** [comment]
I just upgraded from 2.6.2 to 3.1 and I'm getting private prop errors again
`22:67 Uncaught TypeError: cannot modify private _from`

In my code i am doing this:
```
import { Model } from 'objectmodel'
Model.conventionForPrivate = (key) => { return key[0] === '#' }
```
Are there any breaking changes perhaps?

**Comment by beebase** [comment]
ah ok.

> Model.conventionForPrivate and Model.conventionForConstant have been moved to Model.prototype so that you can change these conventions specifically by model

**Comment by sylvainpolletvillard** [comment]
yes, just change `Model.conventionForPrivate` to `Model.prototype.conventionForPrivate`

**Comment by gotjoshua** [comment]
I think a small example in the docs to make this explicit could be helpful. I spent a bit more time that I would have liked to find this hint...
