### ISSUE TITLE
More StandardModels

### ISSUE THREAD

**Issue by furesoft** [sylvainpolletvillard/ObjectModel#5]
Pls add new standard models like to add PrimeNumber to a basic lib

**Comment by sylvainpolletvillard** [comment]
I want to keep the lib as small as possible, but I can publish a collection of usual models definitions or advanced examples depending on your needs. Anyway, there are no standards here.

**Comment by sylvainpolletvillard** [comment]
Is that what you are looking for ? http://objectmodel.js.org/#common-models

**Comment by sylvainpolletvillard** [comment]
closing this one. Feel free to PM me if you need another examples of models definitions.
