### ISSUE TITLE
How to use on NodeJS?

### ISSUE THREAD

**Issue by jesse1983** [sylvainpolletvillard/ObjectModel#50]
How to use with `CommonJS` or `ESModule`?

**Comment by sylvainpolletvillard** [comment]
Use the [UMD build](https://github.com/sylvainpolletvillard/ObjectModel/blob/master/dist/object-model.umd.js) (Universal Module Definition). It works for CommonJS modules, AMD modules and global variable as a fallback.

ES Modules with tree shaking is coming in v3... soon

**Comment by jesse1983** [comment]
Tks!
