### ISSUE TITLE
package.json module entry should points to compiled sources

### ISSUE THREAD

**Issue by darkowic** [sylvainpolletvillard/ObjectModel#54]
```
ERROR in vendor.f3ca509cb6487d3d6fd2.js from UglifyJs
Unexpected token: operator (>) [vendor.f3ca509cb6487d3d6fd2.js:111600,27]
```
```
/***/ }),

/***/ "./node_modules/objectmodel/dist/object-model.js":
/***/ (function(module, exports, __webpack_require__) {

/*!
 * Objectmodel v3.1.0
 * http://objectmodel.js.org
 *
 * Copyright (c) 2017 Sylvain Pollet-Villard
 * Licensed under the MIT license
 */

(function (global, factory) {
	 true ? factory(exports) :
	typeof define === 'function' && define.amd ? define(['exports'], factory) :
	(factory((global.window = global.window || {})));
}(this, (function (exports) { 'use strict';

const _constructor = "_constructor";
const _validate = "_validate";
const ObjectProto     = Object.prototype;
const bettertypeof    = x => ObjectProto.toString.call(x).match(/\s([a-zA-Z]+)/)[1];
```

It is problem with `module` entry. It should point to compiled es6 sources.
https://github.com/jsforum/jsforum/issues/5
https://github.com/rollup/rollup/wiki/pkg.module

Similar issues:
https://github.com/shuhei/material-colors/issues/13
https://github.com/Hypercubed/mini-signals/issues/16
https://github.com/vesparny/brcast/issues/7

This problem loves me :laughing:

**Comment by darkowic** [comment]
Okay, I see in issue #53 that you dropped support for browsers that not support es6 features :/

**Comment by sylvainpolletvillard** [comment]
Yes, v3 relies on ES6 Proxies and is for ES6 compliant browsers. You can still use v2 if you need broader browser support. See release changelog https://github.com/sylvainpolletvillard/ObjectModel/releases/tag/v3.0.0 for details
