### ISSUE TITLE
ES6 Example

### ISSUE THREAD

**Issue by senycorp** [sylvainpolletvillard/ObjectModel#55]
Hi,

can you give me a full ES6 example with imports and typings?

Thx

Selcuk

**Comment by sylvainpolletvillard** [comment]
All the code examples on the documentation website are already in ES6. You can also test them directly in the browser console, the Model classes have been imported and declared as globals.

You also have an example on the README:  https://github.com/sylvainpolletvillard/ObjectModel#basic-usage-example

**Comment by senycorp** [comment]
I am trying to use the class-syntax for model definition:

```javascript
import { ObjectModel } from 'objectmodel/src';

class Notification extends ObjectModel({
  id: Number,
  title: String,
  icon: String,
}) {
  getId() {
    return this.id;
  }
}

window.NOT = Notification;

export default Notification;

```

When i try to create an instance i get following error:

![selection_033](https://user-images.githubusercontent.com/938982/31287904-311f95ae-aac3-11e7-86b1-4340d1073ec6.png)

**Comment by sylvainpolletvillard** [comment]
What is `objectmodel/src` ? Unless you changed the resolution path using a custom webpack config or something, src is a folder, not a module. Try with `import { ObjectModel } from 'objectmodel'`

**Comment by senycorp** [comment]
I have tried ObjectModel too...

```javascript
import { Model } from 'objectmodel'

export default class Breadcrumb extends Model({title: String, icon: [String], link: String}) {

}
```

![selection_034](https://user-images.githubusercontent.com/938982/31312069-9505813a-abba-11e7-9c1b-10187850a229.png)

**Comment by sylvainpolletvillard** [comment]
As you can see on your screenshot, there is no reference to ObjectModel at all in this call stack. The error is in your code, and I can't help you with that...

**Comment by senycorp** [comment]
Can you explain which file should be loaded by importing 'objectmodel'? There is no index.js in the npm package?1

**Comment by sylvainpolletvillard** [comment]
What about this one ? https://github.com/sylvainpolletvillard/ObjectModel/blob/master/src/index.js

**Comment by senycorp** [comment]
Okay. Thanks a lot for your support and this great library.
