### ISSUE TITLE
TypeError: (intermediate value).apply is not a function

### ISSUE THREAD

**Issue by xorock** [sylvainpolletvillard/ObjectModel#58]
Hello.
I'm new to Object Model so maybe it's my fault. I'm trying to use simple code from http://objectmodel.js.org/#doc-es6-classes

Character.js
```
import { Model, BasicModel, ObjectModel } from "objectmodel" 
 
export default class Character extends Model({ lastName: String, firstName: String }){
   get fullName(){ return `${this.firstName} ${this.lastName}`; }
}
```

index.js
```
import Character from './Character'
const rick = new Character({ lastName: "Sanchez", firstName: "Rick" }); // *1
console.log(rick);
```

Line *1 throws error TypeError: (intermediate value).apply is not a function.
What am I doing wrong?

webpack: 3.8.1

**Comment by sylvainpolletvillard** [comment]
Hello,

This code works perfecly fine, you can try in in your browser console  :
![image](https://user-images.githubusercontent.com/566536/32677423-ab926468-c65e-11e7-9ef9-71be5db2d0e7.png)

I suspect there is something wrong in your build setup. Remember that ObjectModel v3.x requires an ES6 target environment, so you should not use Babel to transpile your code to ES5.

**Comment by sylvainpolletvillard** [comment]
closed due to inactivity
