### ISSUE TITLE
the module performance ? 

### ISSUE THREAD

**Issue by ipengyo** [sylvainpolletvillard/ObjectModel#62]
- Native object read and write at 300w/s
- The object of this module is at 30w/s

**Comment by ipengyo** [comment]
performance testing

**Comment by sylvainpolletvillard** [comment]
Did you read "What is the impact on performance ?" in http://objectmodel.js.org/#common-questions ?

**Comment by sylvainpolletvillard** [comment]
If hou have any suggestion on how to improve performance, please let me know. I close this issue since I don't see the point of it.
