### ISSUE TITLE
Setting custom validation messages

### ISSUE THREAD

**Issue by kushubham9** [sylvainpolletvillard/ObjectModel#66]
Hi,
Can I set a custom validation message with each attribute I define in a model?

Something like:
```
const Order = new ObjectModel({
	product: { name: String, quantity: Number, _errorMessage:'custom error message' },
	orderDate: Date
});
```

This will be highly helpful, in building custom API responses.

**Comment by sylvainpolletvillard** [comment]
Hi,
You can define a custom error collector for your model. The errors received contain the attribute name, the expected definition, the actual value, and the original message of the library. This should be enough to make your own messages/ errors and throw them to your end user.

**Comment by sylvainpolletvillard** [comment]
Can I close this issue ?
