### ISSUE TITLE
SetModel.add() throws error

### ISSUE THREAD

**Issue by gotjoshua** [sylvainpolletvillard/ObjectModel#69]
`inherit.js:85 Uncaught TypeError: TypedVOsetmodel.add is not a function`

should SetModel() return a Set?

maybe it just needs more examples and documentation.

(thanks for the amazing work - loving the library)

**Comment by sylvainpolletvillard** [comment]
Hi,

Could you share your whole code ? I don't know what TypesVOsetmodel is.

To answer your question: SetModel() returns a SetModel, just like Model() returns a Model. Once you created your SetModel, then you can use it as a Set constructor.

There is an example here : http://objectmodel.js.org/#doc-set-models ; this is basically all you need to know, as it follows the same principle that the other types of models.

**Comment by gotjoshua** [comment]
Ok, so the bit I was missing is that I need to first define the SetModel with an array of what is allowed inside, and then create an instance of that Model with actual contents. 

Its true, the docs DO show that, but I think i got confused because they also refer to the above example and don't have any comments about what is being returned and what is required.

Anyway, I fixed and posted my code here: https://codepen.io/gotjoshua/pen/WyRwbX
Everything interesting is in the console. 
(I hot-linked to your /dist/ folder for the object-model.js 
cuz i didn't find you on any js cdn yet - is that cool?)

**Comment by sylvainpolletvillard** [comment]
Yes, you got confused between the model and the instance. Here is the corrected code:
```js
let TypedVOsetmodel = new SetModel(TypedVO);
let typedVOset = new TypedVOsetmodel(normalSet);

typedVOset.add(second)
console.log(typedVOset)
console.log(normalSet)
```

To avoid confusion, follow the naming convention where Models all start with an uppercase letter while instances (your data) start with a lowercase letter.

objectmodel.js.org is hosted on Github Pages, it's not really meant to be a CDN. If you need a CDN, I suggest you https://unpkg.com/ ; for the latest version : https://unpkg.com/objectmodel 

I will update the docs with more comments for this section. Feel free to propose pull requests to the docs too if you see improvements to do.

**Comment by sylvainpolletvillard** [comment]
I updated the docs with a CDN link and some changes to  the Set models docs

**Comment by sylvainpolletvillard** [comment]
Regarding your question in the pen:
```js
//this._prot="VO"+VO.staticInstanceCount++ //not allowed - but i would expect to be allowed to set my own private var
```

You are not allowed private access here because you are in the extended class constructor, and this function is not part of the model. You can fix it by declaring a setter in the model:
```js
class VO extends ObjectModel({
	VOCLASSNAME : [String],
	_prot       : [String],
	_priv       : [String],
	isValid : FunctionModel().return(Boolean)
}).defaults({
	isValid : function(){ return true; },
	setProt(value){ this._prot = value }
})
{
	constructor(modelDefinition)
	{
		super(modelDefinition)
		this.setProt("VO"+VO.staticInstanceCount++)
		console.log(this.VOCLASSNAME+"(VO) instance number: " + VO.staticInstanceCount++);
	}
```

or by assigning the private property in the model constructor (the super() call):

```js
class VO extends ObjectModel(
	{
		VOCLASSNAME : [String],
		_prot       : [String],
		_priv       : [String],
		isValid : FunctionModel().return(Boolean)
	}).defaults({
		isValid : function(){ return true; }
	})
{
	constructor(modelDefinition)
	{
		super({ ...modelDefinition, _prot: "VO"+VO.staticInstanceCount++ })
		console.log(this.VOCLASSNAME+"(VO) instance number: " + VO.staticInstanceCount++);
	}
```

**Comment by gotjoshua** [comment]
great! thanks! 

I updated the pen with the unpkg link

... and I will consider your above suggestions... I had already played with the setter, but not considered the second option.

 I'm also curious about your answer to the other [issue](https://github.com/sylvainpolletvillard/ObjectModel/issues/70) i opened about protected props and methods.
