### ISSUE TITLE
function model - allowing Object

### ISSUE THREAD

**Issue by furesoft** [sylvainpolletvillard/ObjectModel#7]
Hi,
if ill using Object as function argument model, it will throw an error if ill use any object like number or string as argument. so it ust be possible to allow any type in the same modeling syntax or like Model.Primitive

**Comment by sylvainpolletvillard** [comment]
Note that primitives are not objects: they do not inherit from Object.prototype by default.

Besides null and undefined, there are only 3 primitives in ES5: String, Boolean, Number ; and 4 in ES6 with the addition of Symbol. So you can easily use an enumeration here: 
```
Model.Primitive = [String, Boolean, Number, Symbol]
```

If you want a property to allow *any* type, it does not make sense to put it in the model definition as there will be no validation required at all.
