### ISSUE TITLE
Where do the docs live?

### ISSUE THREAD

**Issue by gotjoshua** [sylvainpolletvillard/ObjectModel#71]
I thought about making a fork to offer some suggestions for docs updates, but got confused... The docs in the docs folder seem to be out of date, are you updating directly via index.html in the root folder of the repo?

**Comment by sylvainpolletvillard** [comment]
Yup, it's `index.html` in the root folder. See my last commit, I updated the docs

**Comment by gotjoshua** [comment]
got it. thanks!

and thanks again for your great library and active responses...
