### ISSUE TITLE
Improvements to the custom dev formatter

### ISSUE THREAD

**Issue by sylvainpolletvillard** [sylvainpolletvillard/ObjectModel#76]
Goals:

- [x] show undeclared props in the model instance formatter
- [x] show the prototype in the model instance formatter
- [x] distinct color code between model and model instances
- [x] improve formatting of Array, Set and Map models
- [x] show default values in the model formatter
- [x] specific style for private properties
- [x] specific style for constant properties
- [x] specific style for private and constant properties
- [x] specific style for sealed object models
- [x] color palette review
- [x] improve formatting of set,map and array models instances
- [x] bypass proxy to show the original object in logs when possible
- [x] show assertions in the model formatter
- [x] use extendable submodels definitions
- stay clean, non-bloated
- stay accessible and visually intuitive
- stay technically accurate

Current progress:

```js
M = ObjectModel({
    _private: [Number],
    CONSTANT: Number,
    _PRIVATECONSTANT: Boolean,
    property: [String],
    arrayProp: ArrayModel(Number), 
    setProp: SetModel(String),
    mapProp: MapModel(String, Number),
    method: FunctionModel(Event).return(Boolean)   
})
.as("MyModel")
.defaults({
    _private: undefined,
    CONSTANT: 37.5,
    _PRIVATECONSTANT: true,
    property: "default",
    arrayProp: [],
    setProp: new Set(["root"]),
    mapProp: new Map([["root", 0]]),
    method(){ return false }
});
m = new M({
    property: 'test',
    undeclaredProp: 9,
    setProp: new Set(["a","b","c"]),
    method(e){ return !!e }
});
console.log(M, m);
```
![image](https://user-images.githubusercontent.com/566536/41671047-4960b0d6-74b6-11e8-9930-f5c75c1211b8.png)

**Comment by sylvainpolletvillard** [comment]
@gotjoshua what do you think ? I'm happy with the current design

**Comment by gotjoshua** [comment]
screenshot looks great! Looking forward to test it out (tomorrow morning i'll have time) Will you push it to npm?

**Comment by sylvainpolletvillard** [comment]
yes I'll publish a new version, probably minor

**Comment by gotjoshua** [comment]
Mostly perfect... found one thing:

let PlacesOMset=new SetModel([PlaceOM])
let clientSpaceOM = new SpaceOM(
	{
		name: 'clientSpacenew',
		places: new PlacesOMset(normalSet)
	}
);
clientSpaceOM.undecProp='foo'
clientSpaceOM.undecArrayWithDups=arrayWithDupObj;
clientSpaceOM.undecSetFromArray=normalSet;

i am expecting places to show like your setProp: Set of SpaceOM >
but it just shows as places: model and is not expandable:
![spaceom](https://user-images.githubusercontent.com/8686454/41703365-f068efb4-752a-11e8-9c56-c563f3e1b126.png)

**Comment by sylvainpolletvillard** [comment]
Ah, you mean expandable model definitions *inline* inside another parent model definition. It may be possible, but I'm gonna need to rewrite the whole model formatter (currently relying on the `toString()` behaviour that expands everything as a String)

**Comment by gotjoshua** [comment]
ouch. well i don't mean to be demanding, i just thought it would be easy enough because it already works for a normal Set, so why not for an instance of a SetModel...

Also down in the __proto Model - i would expect places: Set of PlaceOM >
(that could be expandable or not at that depth)...

But yeah, I meant if a Prop is typed as a SetModel - when I fill that Prop with an instance of a SetModel - i expect that the SetModel will check if all items are instances of the allowed Object Type and i expect to be able to inspect the Set...

And I just notice now that in the __proto, constructor: ought to align to the top with >Model

**Comment by sylvainpolletvillard** [comment]
I'm afraid alignment is not something I can easily control. The custom formatter API is quite limited and very badly documented by Google.

I reused the `toString` logic of each model in the formatter to keep the formatter code small and avoid code duplication. But if there is a legitimate reason to customize this logic for the devtools, for example using the expandable structures, I can do that. The code size of the formatter shouldn't be a problem since you are not supposed to ship it in production.

**Comment by gotjoshua** [comment]
Fully understandable. I consider it a "nice to have" to show the expandable structures - but if I am stuck and need to see it - I can always toggle off the custom formatting for a hot second. So i wouldn't give it high priority.

**Comment by sylvainpolletvillard** [comment]
Further improvements to instance formatter:
![image](https://user-images.githubusercontent.com/566536/41740022-1e3c6d78-7597-11e8-8dd7-323ad31ebd6b.png)

**Comment by sylvainpolletvillard** [comment]
Showing assertions in the model formatter:
![image](https://user-images.githubusercontent.com/566536/41743945-9cdf1a08-75a2-11e8-95cb-d881736f3039.png)

**Comment by sylvainpolletvillard** [comment]
Expandable submodels, cc @gotjoshua 
![image](https://user-images.githubusercontent.com/566536/41746910-5d51fd10-75ac-11e8-82ab-05247e509471.png)
