### ISSUE TITLE
"Can't find variable: initModel" in all browser in iOS 10.1.1

### ISSUE THREAD

**Issue by edmundyipll** [sylvainpolletvillard/ObjectModel#82]
I am developing my project using v3.5.2, at first everything is fine and work in all browsers but when I start testing in iOS 10.1.1,
The whole page won't load and a console error came out, "Can't find variable: initModel"

Would like to ask for some help here, thanks..

**Comment by sylvainpolletvillard** [comment]
Hi,
I don't have an iOS device to test, so I'm open to external help. In theory, iOS 10.1.1 has full ES6 support, but it may have bugs. Through the error message is weird. Would it be possible to provide the full stack trace of the error ?

**Comment by edmundyipll** [comment]
Thanks for the reply,
Here's the screenshot of the error stack,,

![image](https://user-images.githubusercontent.com/25522646/42252529-aa62fb1e-7f6f-11e8-9fd9-3803b959c47e.png)

*BasicModels.js stores only the basic predefined models,, like the examples in the docs,,

BasicModels.js
![image](https://user-images.githubusercontent.com/25522646/42252716-74cd8da6-7f70-11e8-9710-6bbe3fe2c2e1.png)

**Comment by edmundyipll** [comment]
I am using webpack@4.8.3 ,, with vue-cli 3,,

**Comment by sylvainpolletvillard** [comment]
Closed as outdated and non reproducible. Please create a new issue if this is still a problem with latest version
