### ISSUE TITLE
Assertion that is based on the value of another property

### ISSUE THREAD

**Issue by gotjoshua** [sylvainpolletvillard/ObjectModel#86]
We have a model that requires the comments property to be non-empty if status property == 'blocked'

Is it possible to make an assertion for one prop that depends on another?

**Comment by sylvainpolletvillard** [comment]
Something like that ?

```js
const MyModel = ObjectModel({ 
  comments: ArrayModel(String),
  status: String
}).assert(o => o.status !== 'blocked' || o.comments.length > 0, 
  "requires the comments property to be non-empty if status property == 'blocked'")
```

**Comment by gotjoshua** [comment]
nearly perfect!

I went with:
```js
const MyModel = ObjectModel({ 
  comments: ArrayModel(String),
  status: String
}).assert(o => o.status !== 'blocked' || !! o.comments, 
  "requires the comments property to be non-empty if status property == 'blocked'")
```

as undefined comments have no length (maybe also because I am using String as my comments type - why do you suggest ArrayModel(String) ? )

Thanks once again!

**Comment by sylvainpolletvillard** [comment]
I don't know what the type of your variable was, I guess it was an array because you use the plural form, which is a popular convention. If it is an optional string, change the definition to `comments: [String]`
