### ISSUE TITLE
Definition of nested list models

### ISSUE THREAD

**Issue by gibelium** [sylvainpolletvillard/ObjectModel#89]
First of all thank you for this awesome library. We use it within meteor and are pretty happy.

Today I came across the definition and default initialization of nested list-models (e.g. ArrayModel and SetModel). Defining the property itself is straight forward, but defining a mandatory list-model to be empty by default took me some time and feels a little bit unhandy or let's say I assumed to be different. I used version 4 from the examples default initialization and wondered why it does not work as it does not throw an error during runtime.

Please find a simple [codepen example](https://codepen.io/gibelium/pen/vavQZN) underneath.

My first question is if you can imagine to simplify the definition of a list models default value for instance with a basic javascript array syntax. This at least could be "[]" defining a empty array/set. Perhaps this syntax can also be used for initializing a list model with actual default values.

My second question came up while creating the example. Why does version 2 work with and without the new operator?

Thank you and regards,
Sebastian

### Example Code

```js
class NestedVO extends ObjectModel({
  numberProperty: Number,
}).defaults({
  numberProperty: 0,
}) {
  constructor(modelDefinition) {
    super(modelDefinition);
  }
}
const NestedVOSetModel = SetModel(NestedVO);
//NestedVOSetModel.add(new NestedVO({ numberProperty: 1 }))
console.log(NestedVOSetModel);
const NestedStringsSetModel = SetModel(String);
class VO extends ObjectModel({
  stringProperty: String,
  nestedStringsSetModel: NestedStringsSetModel,
  nestedVOsSetModel: NestedVOSetModel ,
  nestedStringsArrayModel: ArrayModel(String),
  nestedVOsArrayModel: ArrayModel(NestedVO),
}).defaults({
    // 1) explicitly predefined Model const
  nestedStringsSetModel: NestedStringsSetModel( [] ), 

    // 2) works with or without new (also true for 1) 
  nestedVOsSetModel: new NestedVOSetModel( [] ), 

    // 3) most concise working syntax
  nestedStringsArrayModel: ArrayModel(String)([]), 

    // 4) doesn't work, but wishing it would ; - )
  nestedVOsArrayModel: [], 
}) {
  constructor(modelDefinition) {
    super(modelDefinition);
  }
}

let normalVO = new VO({ stringProperty: 'Test String' });
console.log('normalVO.stringProperty: ' + normalVO.stringProperty);

// Add String properties to SetModel
console.log(
  'Size of String SetModel (before): ' + normalVO.nestedStringsSetModel.size
);
normalVO.nestedStringsSetModel.add('first ');
normalVO.nestedStringsSetModel.add('second');
normalVO.nestedStringsSetModel.add('third');
console.log(
  'Size of String SetModel (after): ' + normalVO.nestedStringsSetModel.size
);

// Add String properties to ArrayModel
console.log(
  'Size of String ArrayModel (before): ' + normalVO.nestedStringsArrayModel.length
);
normalVO.nestedStringsArrayModel.push('first');
normalVO.nestedStringsArrayModel.push('second');
normalVO.nestedStringsArrayModel.push('third');
console.log(
  'Size of String ArrayModel (after): ' + normalVO.nestedStringsArrayModel.length
);

// Add nested objects to SetModel
console.log(
  'Size of NestedVO SetModel (before): ' + normalVO.nestedVOsSetModel.size
);
normalVO.nestedVOsSetModel.add(new NestedVO({ numberProperty: 1 }));
normalVO.nestedVOsSetModel.add(new NestedVO({ numberProperty: 2 }));
normalVO.nestedVOsSetModel.add(new NestedVO({ numberProperty: 3 }));
console.log(
  'Size of NestedVO SetModel (after): ' + normalVO.nestedVOsSetModel.size
);

// Add nested objects to ArrayModel
console.log(
  'Size of NestedVO ArrayModel (before): ' + normalVO.nestedVOsArrayModel.length
);
normalVO.nestedVOsArrayModel.push(new NestedVO({ numberProperty: 1 }));
normalVO.nestedVOsArrayModel.push(new NestedVO({ numberProperty: 2 }));
normalVO.nestedVOsArrayModel.push(new NestedVO({ numberProperty: 3 }));
console.log(
  'Size of NestedVO ArrayModel (after): ' + normalVO.nestedVOsArrayModel.length
);
```

**Comment by gibelium** [comment]
In a breakpoint on the second normalVO.nestedVOsArrayModel.push command (near the bottom at line 72), one can see that normalVO.nestedVOsArrayModel IS a Proxy of an Array instance with length 0. One would expect these push statements to function:

![objectmodelnestedarraymodelproxy](https://user-images.githubusercontent.com/728680/43969593-901450d0-9cc2-11e8-98c9-c306fe44131d.png)

**Comment by sylvainpolletvillard** [comment]
Hi, thanks for the detailed issue. I am currently on vacation and will check this out next week.

**Comment by gibelium** [comment]
Thank you for your quick investigation.

I now ended up with a private factory function that is called by the constructor and creating the new instance of the array/set/map models there, which is most elegant for mandatory list models from my point of view.

**Comment by sylvainpolletvillard** [comment]
I also think it is the most elegant solution currently available. I keep in mind that defaults assignment needs a rework for future versions of ObjectModel. Other libraries separate data and methods to differ between prototype assignment and constructor assignment, but I don't really like this pattern. Sometimes you legit need to put some values in the prototype or at the contrary have some functions not in the prototype. Another option would be to dynamically assign everything and let the user manually put stuff in the prototype of he knows what he is doing. There is a compromise to find between simplicity vs convenience.

**Comment by sylvainpolletvillard** [comment]
I started to work on the default assignment rework. It will imply breaking changes, so I keep it for ObjectModel v4. Here is the current proposal:
- rename model.defaultTo method to model.defaults
- change objectModel.defaults method: it no longer changes the model prototype, but let you set default values for nested properties. To get the original behaviour, manually assign to the prototype or use a class.
- if a function is passed to model.defaults method, and if the model is not a function model, then this function will be called and the returned value will be used as default value. This is useful to get around the common reference problem you encountered previously.

Another option would be to enforce always passing a function to the defaults method. It's a bigger change that will increase migration time, but it will ensure library users to never fall again into this trap.

What do you think ?
