### ISSUE TITLE
API update() function

### ISSUE THREAD

**Issue by gotjoshua** [sylvainpolletvillard/ObjectModel#90]
Feature Request:
We have a wish for a function that can do basically the same as ObjectModel({initObject}) with an {updateObject}, without destroying the initial instance/reference.

Wished Pseudo-Code Ex:

```js
mInstance = ObjectModel({id:Number,info:String})({id:1,info:'init'});
mInstance.update({info:'newString'};
```

any chance you could save us some for looping with such a function?

**Comment by sylvainpolletvillard** [comment]
What would be the difference with `Object.assign(mInstance, { info })` ?

**Comment by sylvainpolletvillard** [comment]
Regarding new API proposals, something to keep in mind is that models aimed to be transparent wrappers around any kind of value/object. So we can't really modify instance prototypes, we can only act on the model layer. Such an addition would break every existing code using an object with an `update` property, so it is likely to cause damage.

**Comment by gotjoshua** [comment]
Yeah, good call... sometimes i seem to overlook the obvious, in my enthusiasm for the library...

Object assign should work anyway, as OM will check everything. Thanks again (for yet another basic js lesson : - /   )
